/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/Image copy.vue')['default']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    GroupModal: typeof import('./src/components/Group-Modal/index.vue')['default']
    Image: typeof import('./src/components/Image.vue')['default']
    'Image copy': typeof import('./src/components/Image copy.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    LoginModal: typeof import('./src/components/Login-Modal/index.vue')['default']
    Modal: typeof import('./src/components/Modal/index.vue')['default']
    SettingsModal: typeof import('./src/components/Settings-Modal/index.vue')['default']
    Tag: typeof import('./src/components/Tag.vue')['default']
    Toast: typeof import('./src/components/Toast/index.vue')['default']
    UseModal: typeof import('./src/components/Use-Modal/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
